behaviors:
  BoxingAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048      # Zmniejszone dla początku
      buffer_size: 10240    # Zmniejszone
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    
    network_settings:
      normalize: true
      hidden_units: 256     # Zmniejszone dla początku
      num_layers: 2         # Zmniejszone
      vis_encode_type: simple
      # Usuń memory na początek - może powodować problemy
    
    reward_signals:
      extrinsic:
        gamma: 0.99         # Zmniejszone
        strength: 1.0
      # Usuń curiosity na początek - upraszcza trening
    
    self_play:
      save_steps: 10000
      team_change: 50000
      swap_steps: 5000
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
    
    max_steps: 500000       # Zmniejszone dla testów
    time_horizon: 1000
    summary_freq: 5000      # Częstsze raporty
    threaded: false         # Wyłącz na początek